name: Build .NET Desktop App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x' # Ganti jika kamu pakai versi lain

    - name: Restore dependencies
      run: dotnet restore RobloxExecutorCSharp/RobloxExecutorCSharp/RobloxExecutorCSharp.sln

    - name: Build
      run: dotnet build RobloxExecutorCSharp/RobloxExecutorCSharp/RobloxExecutorCSharp.sln --configuration Release --no-restore

    - name: Publish
      run: dotnet publish RobloxExecutorCSharp/RobloxExecutorCSharp/RobloxExecutorCSharp.csproj --configuration Release --output ./publish --no-build

    - name: List published files
      run: dir publish
