name: Build .NET Framework Project

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Restore NuGet packages
      run: nuget restore RobloxExecutorCSharp/RobloxExecutorCSharp/RobloxExecutorCSharp.sln

    - name: Build with MSBuild
      run: msbuild RobloxExecutorCSharp/RobloxExecutorCSharp/RobloxExecutorCSharp.sln /p:Configuration=Release
